//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphasoftWebsite.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatMessage
    {
        public int ChatMessageId { get; set; }
        public Nullable<System.DateTime> ChatMessageDateTime { get; set; }
        public string Message { get; set; }
        public string UserName { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
