//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphasoftWebsite.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HostType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HostType()
        {
            this.SmtpHosts = new HashSet<SmtpHost>();
        }
    
        public int HostTypeId { get; set; }
        public string HostTypeName { get; set; }
        public string HostName { get; set; }
        public string PortNumber { get; set; }
        public bool IsActive { get; set; }
        public bool EnableSsl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SmtpHost> SmtpHosts { get; set; }
    }
}
