//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphasoftWebsite.Core.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlphasoftWebsiteContext : DbContext
    {
        public AlphasoftWebsiteContext()
            : base("name=AlphasoftWebsiteContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<BlogCategory> BlogCategories { get; set; }
        public virtual DbSet<ChatMessage> ChatMessages { get; set; }
        public virtual DbSet<ChatUser> ChatUsers { get; set; }
        public virtual DbSet<CompanyDetail> CompanyDetails { get; set; }
        public virtual DbSet<CompanySocialAccountDetail> CompanySocialAccountDetails { get; set; }
        public virtual DbSet<ConnectionProperty> ConnectionProperties { get; set; }
        public virtual DbSet<Designation> Designations { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<FactorDetail> FactorDetails { get; set; }
        public virtual DbSet<FactorHeader> FactorHeaders { get; set; }
        public virtual DbSet<FAQ> FAQs { get; set; }
        public virtual DbSet<FeatureDetail> FeatureDetails { get; set; }
        public virtual DbSet<FeatureHeader> FeatureHeaders { get; set; }
        public virtual DbSet<HomeBanner> HomeBanners { get; set; }
        public virtual DbSet<IconList> IconLists { get; set; }
        public virtual DbSet<NewsletterMail> NewsletterMails { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductCategory> ProductCategories { get; set; }
        public virtual DbSet<ResetPassword> ResetPasswords { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<ServiceProperty> ServiceProperties { get; set; }
        public virtual DbSet<SocialAccountType> SocialAccountTypes { get; set; }
        public virtual DbSet<Software> Softwares { get; set; }
        public virtual DbSet<SoftwareCategory> SoftwareCategories { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<LoginInfo> LoginInfoes { get; set; }
        public virtual DbSet<FAQHeader> FAQHeaders { get; set; }
        public virtual DbSet<SentMailLog> SentMailLogs { get; set; }
        public virtual DbSet<NewsletterSubscriber> NewsletterSubscribers { get; set; }
        public virtual DbSet<Pricing> Pricings { get; set; }
        public virtual DbSet<PricingDetail> PricingDetails { get; set; }
        public virtual DbSet<PricingDetailType> PricingDetailTypes { get; set; }
        public virtual DbSet<PricingTableType> PricingTableTypes { get; set; }
        public virtual DbSet<SmtpHost> SmtpHosts { get; set; }
        public virtual DbSet<HostType> HostTypes { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<ClientList> ClientLists { get; set; }
        public virtual DbSet<OnlineUserFeedBackDetail> OnlineUserFeedBackDetails { get; set; }
    }
}
