//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphasoftWebsite.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsletterSubscriber
    {
        public int NewsletterSubscriberId { get; set; }
        public string NewsletterSubscriberEmail { get; set; }
        public string MachineIP { get; set; }
        public Nullable<System.DateTime> SubscriptionDate { get; set; }
        public bool IsActive { get; set; }
    }
}
