//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphasoftWebsite.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineUserFeedBackDetail
    {
        public int UserFeedBackId { get; set; }
        public string UserFullName { get; set; }
        public string UserEmail { get; set; }
        public string UserMessageSubject { get; set; }
        public string UserMessage { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string MachineIP { get; set; }
    }
}
