//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphasoftWebsite.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PricingDetail
    {
        public int PricingDetailID { get; set; }
        public int PricingTableTypeID { get; set; }
        public int PricingDetailTypeID { get; set; }
        public string PricingDetailQuantity { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int UpdatedBy { get; set; }
    
        public virtual PricingDetailType PricingDetailType { get; set; }
        public virtual PricingTableType PricingTableType { get; set; }
    }
}
